# Header
navbar_brand: Fundamentals of Interactive Design
menu:
  Home: index.html
  Slides: slides/
  Syllabus: syllabus/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
- slide_list
- useful_links
about_widget_content: >
  <p>This is the website for my Fundamentals of Interactive Design at Seminole State College in Heathrow Florida.</p>

# widget behavior
archive_type: 'category'
show_count: true

# Miscellaneous
google_analytics: UA-58547762-1
favicon:
twitter_id: planetoftheweb
google_plus:
fb_admins:
fb_app_id:
